on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/library/debian:bookworm
    steps:

    - name: Install git
      run: |
        apt update && apt install -y git curl

    - name: Checkout actions
      run: |
        git clone ${{ github.server_url }}/indigoparadox/actions actions

    - name: Setup default source
      uses: ./actions/debdefault

    - name: Setup auxilliary source
      uses: ./actions/debapt
      with:
        repos: forgejo-packaging+https://forgejo.interfinitydynamics.info/api/packages/packaging/debian+https://forgejo.interfinitydynamics.info/api/packages/packaging/debian/repository.key forgejo-devkitpro+https://forgejo.interfinitydynamics.info/api/packages/devkitpro/debian+https://forgejo.interfinitydynamics.info/api/packages/devkitpro/debian/repository.key
    
    - name: Install build prerequisites
      run: |
        apt update && apt install -y build-essential libsdl2-dev libsdl2-mixer-dev xxd zip liballegro4-dev mkisofs watcom-sdl imagemagick retro68 file nds-dev

    - name: Install OpenSSH and setup keys
      uses: ./actions/openssh
      with:
        deploy-key: "${{ secrets.DEPLOYKEY }}"
        ssh-key-algo: ed25519
   
    - name: Checkout repo
      uses: ./actions/checkout
      with:
        remote-ssh-port: ${{ vars.SSHPORT }}

    - name: "Build binary - html"
      continue-on-error: true
      uses: ./actions/buildemcc
      with:
        bin-name: mbean.html

    - name: "Upload to web"
      uses: ./actions/scp
      with:
        asset-files: mbean.html mbean.js mbean.wasm unscii_8.hex
        remote-ssh-user: ${{ secrets.WASMUSER }}
        remote-ssh-host: ${{ vars.WASMHOST }}
        remote-path: ${{ vars.WASMPATH }}
        remove-first: true
        mkdir-first: true

    - name: Create tag on IFDY
      uses: ./actions/taghead
      with:
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2IFDY }}

    - name: Create tag on Codeberg
      uses: ./actions/taghead
      with:
        remote-site: https://codeberg.org
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2CB }}

    - name: "Build binary - NDS"
      continue-on-error: true
      uses: ./actions/build
      with:
        bin-name: mbean.nds

    - name: "Upload binary - NDS IFDY"
      continue-on-error: true
      uses: ./actions/releases
      with:
        asset-file: mbean.nds
        asset-file-name: mbean-GITDATE-GITHASH.nds
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2IFDY }}

    - name: "Upload binary - NDS Codeberg"
      continue-on-error: true
      uses: ./actions/releases
      with:
        remote-site: https://codeberg.org
        asset-file: mbean.nds
        asset-file-name: mbean-GITDATE-GITHASH.nds
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2CB }}

    - name: "Build binary - UNIX SDL"
      continue-on-error: true
      uses: ./actions/build
      with:
        bin-name: mbeansdl.Linux_x86_64.tgz

    - name: "Upload binary - UNIX SDL IFDY"
      continue-on-error: true
      uses: ./actions/releases
      with:
        asset-file: mbeansdl.Linux_x86_64.tgz
        asset-file-name: mbean-sdl-linux-amd64-GITDATE-GITHASH.tgz
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2IFDY }}

    - name: "Upload binary - UNIX SDL Codeberg"
      continue-on-error: true
      uses: ./actions/releases
      with:
        remote-site: https://codeberg.org
        asset-file: mbeansdl.Linux_x86_64.tgz
        asset-file-name: mbean-sdl-linux-amd64-GITDATE-GITHASH.tgz
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2CB }}

    - name: "Build binary - UNIX Allegro"
      continue-on-error: true
      uses: ./actions/build
      with:
        bin-name: mbeanale.Linux_x86_64.tgz

    - name: "Upload binary - UNIX Allegro IFDY"
      continue-on-error: true
      uses: ./actions/releases
      with:
        asset-file: mbeanale.Linux_x86_64.tgz
        asset-file-name: mbean-allegro-linux-amd64-GITDATE-GITHASH.tgz
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2IFDY }}

    - name: "Upload binary - UNIX Allegro Codeberg"
      continue-on-error: true
      uses: ./actions/releases
      with:
        remote-site: https://codeberg.org
        asset-file: mbeanale.Linux_x86_64.tgz
        asset-file-name: mbean-allegro-linux-amd64-GITDATE-GITHASH.tgz
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2CB }}

    - name: "Build binary - UNIX xlib"
      continue-on-error: true
      uses: ./actions/build
      with:
        bin-name: mbeanxlib.Linux_x86_64.tgz

    - name: "Upload binary - UNIX xlib IFDY"
      continue-on-error: true
      uses: ./actions/releases
      with:
        asset-file: mbeanxlib.Linux_x86_64.tgz
        asset-file-name: mbean-xlib-linux-amd64-GITDATE-GITHASH.tgz
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2IFDY }}

    - name: "Upload binary - UNIX xlib Codeberg"
      continue-on-error: true
      uses: ./actions/releases
      with:
        remote-site: https://codeberg.org
        asset-file: mbeanxlib.Linux_x86_64.tgz
        asset-file-name: mbean-xlib-linux-amd64-GITDATE-GITHASH.tgz
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2CB }}

    - name: "Build binary - Windows NT Native"
      continue-on-error: true
      uses: ./actions/build
      with:
        bin-name: mbeannt.zip

    - name: "Upload binary - Windows NT Native IFDY"
      continue-on-error: true
      uses: ./actions/releases
      with:
        asset-file: mbeannt.zip
        asset-file-name: mbean-winnt-x86-GITDATE-GITHASH.zip
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2IFDY }}

    - name: "Upload binary - Windows NT Native Codeberg"
      continue-on-error: true
      uses: ./actions/releases
      with:
        remote-site: https://codeberg.org
        asset-file: mbeannt.zip
        asset-file-name: mbean-winnt-x86-GITDATE-GITHASH.zip
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2CB }}

    - name: "Build binary - Windows 3.x Native"
      continue-on-error: true
      uses: ./actions/build
      with:
        bin-name: mbeanw3.zip

    - name: "Upload binary - Windows 3.x Native IFDY"
      continue-on-error: true
      uses: ./actions/releases
      with:
        asset-file: mbeanw3.zip
        asset-file-name: mbean-win3x-x86-GITDATE-GITHASH.zip
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2IFDY }}

    - name: "Upload binary - Windows 3.x Native Codeberg"
      continue-on-error: true
      uses: ./actions/releases
      with:
        remote-site: https://codeberg.org
        asset-file: mbeanw3.zip
        asset-file-name: mbean-win3x-x86-GITDATE-GITHASH.zip
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2CB }}

    - name: "Build binary - DOS BIOS"
      continue-on-error: true
      uses: ./actions/build
      with:
        bin-name: mbeanb.zip

    - name: "Upload binary - DOS BIOS IFDY"
      continue-on-error: true
      uses: ./actions/releases
      with:
        asset-file: mbeanb.zip
        asset-file-name: mbean-dosb-x86-GITDATE-GITHASH.zip
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2IFDY }}

    - name: "Upload binary - DOS BIOS Codeberg"
      continue-on-error: true
      uses: ./actions/releases
      with:
        remote-site: https://codeberg.org
        asset-file: mbeanb.zip
        asset-file-name: mbean-dosb-x86-GITDATE-GITHASH.zip
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2CB }}

    - name: "Build binary - Mac System 6"
      continue-on-error: true
      uses: ./actions/build
      with:
        bin-name: mbean.m68k.dsk

    - name: "Upload binary - Mac System 6 IFDY"
      continue-on-error: true
      uses: ./actions/releases
      with:
        asset-file: mbean.m68k.dsk
        asset-file-name: mbean-mac6-68k-GITDATE-GITHASH.dsk
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2IFDY }}

    - name: "Upload binary - Mac System 6 Codeberg"
      continue-on-error: true
      uses: ./actions/releases
      with:
        remote-site: https://codeberg.org
        asset-file: mbean.m68k.dsk
        asset-file-name: mbean-mac6-68k-GITDATE-GITHASH.dsk
        api-user: ${{ vars.APIUSER }}
        api-oauth2: ${{ secrets.APIOAUTH2CB }}

